// AUTO-GENERATED by `cargo run -p ciri-protocol --example dump_messages`.
// Do not edit by hand. Regenerate after any change to ClientMessage,
// ServerMessage, or a nested struct referenced by them.

// Compile-time TypeScript shapes that mirror the wire format.
//   * `u64` / `i64` / `usize` are `bigint` (msgpack values may
//     exceed `Number.MAX_SAFE_INTEGER`).
//   * `Vec<u8>` fields are `Uint8Array` — the codec converts
//     to/from the msgpack `[u8]` array shape automatically.
//   * `Option<T>` is `T | null` (msgpack `nil` decodes as `null`).

export type BounceDirection =
  | { tag: "Left" }
  | { tag: "Right" }
  | { tag: "Up" }
  | { tag: "Down" };

export interface CapturePaneOpts {
  scrollbackRows: number;
  joinWrapped: boolean;
  preserveTrailingSpaces: boolean;
}

export type ClientMessage =
  | { tag: "Input"; paneId: bigint; data: Uint8Array; inputSeq: bigint }
  | { tag: "CreatePane" }
  | { tag: "SplitDown" }
  | { tag: "NewTileBelow" }
  | { tag: "ClosePane"; paneId: bigint }
  | { tag: "FocusLeft" }
  | { tag: "FocusRight" }
  | { tag: "FocusUp" }
  | { tag: "FocusDown" }
  | { tag: "MovePaneLeft" }
  | { tag: "MovePaneRight" }
  | { tag: "Resize"; cols: number; rows: number; width: number; height: number; cellWidth: number; cellHeight: number }
  | { tag: "SetColumnWidth"; proportion: number; fixedPx: (number | null) }
  | { tag: "AdjustColumnSplit"; delta: number }
  | { tag: "EqualizeColumnSplit" }
  | { tag: "Attach" }
  | { tag: "Detach" }
  | { tag: "Ack"; generation: bigint }
  | { tag: "MouseInput"; paneId: bigint; button: number; col: number; row: number; pressed: boolean; modifiers: number }
  | { tag: "SwitchWorkspace"; workspaceIdx: bigint }
  | { tag: "ConsumeIntoColumn" }
  | { tag: "ExpelFromColumn" }
  | { tag: "ListSessions"; all: boolean }
  | { tag: "KillSession"; sessionName: string }
  | { tag: "KillServer" }
  | { tag: "SwitchSession"; sessionName: string }
  | { tag: "SetTileWeights"; columnIdx: bigint; topTileIdx: bigint; topWeight: number; bottomWeight: number }
  | { tag: "AdjustColumnSplitAt"; columnIdx: bigint; delta: number }
  | { tag: "FocusChange"; focused: boolean }
  | { tag: "FocusPane"; paneId: bigint }
  | { tag: "SendKeys"; sessionName: string; paneId: bigint; keys: Uint8Array }
  | { tag: "RunCommand"; sessionName: string; command: string; cwd: (string | null) }
  | { tag: "GetSessionInfo"; sessionName: string }
  | { tag: "ListPanes"; sessionName: string }
  | { tag: "FocusPaneById"; sessionName: string; paneId: bigint }
  | { tag: "ClosePaneById"; sessionName: string; paneId: bigint }
  | { tag: "CreatePaneIn"; sessionName: string }
  | { tag: "GetLayout"; sessionName: string }
  | { tag: "ApplyTemplate"; templateName: string; sessionName: string }
  | { tag: "ListTemplates" }
  | { tag: "SaveTemplate"; templateName: string; sessionName: string }
  | { tag: "Ping"; seq: bigint; clientTimeUs: bigint }
  | { tag: "CapturePane"; sessionName: string; paneId: bigint; opts: CapturePaneOpts }
  | { tag: "ListPrompts"; sessionName: string; paneId: bigint }
  | { tag: "JumpToPrompt"; sessionName: string; paneId: bigint; fromOffset: number; direction: number };

export interface ColumnState {
  tiles: (TileState)[];
  activeTileIdx: bigint;
  widthProportion: number;
  widthFixedPx: (number | null);
}

export type ImageDisplayMode =
  | { tag: "Cells" }
  | { tag: "Pixels" };

export interface LayoutState {
  workspaces: (WorkspaceState)[];
  activeWorkspaceIdx: bigint;
}

export interface PaneDetailInfo {
  paneId: bigint;
  cols: number;
  rows: number;
  title: string;
  cwd: (string | null);
  isActive: boolean;
  workspaceIdx: bigint;
  columnIdx: bigint;
  tileIdx: bigint;
}

export interface PromptMarkInfo {
  promptLine: bigint;
  outputLine: (bigint | null);
  doneLine: (bigint | null);
  exitCode: (number | null);
  durationMs: (bigint | null);
}

export type ServerMessage =
  | { tag: "StateSync"; layout: LayoutState; paneIds: (bigint)[] }
  | { tag: "LayoutUpdate"; layout: LayoutState }
  | { tag: "PaneCreated"; paneId: bigint; columnIdx: bigint; cols: number; rows: number }
  | { tag: "PaneClosed"; paneId: bigint }
  | { tag: "ServerShutdown" }
  | { tag: "ClipboardStore"; data: string }
  | { tag: "SessionList"; sessions: (SessionInfo)[] }
  | { tag: "SessionSwitched"; sessionName: string }
  | { tag: "SessionKilled"; sessionName: string }
  | { tag: "Error"; message: string }
  | { tag: "Bell"; paneId: bigint }
  | { tag: "CommandCompleted"; paneId: bigint; durationSecs: bigint; exitCode: (number | null) }
  | { tag: "Notification"; paneId: bigint; title: string; body: string }
  | { tag: "ImagePlacement"; paneId: bigint; imageId: bigint; col: number; row: number; widthCells: number; heightCells: number; pixelWidth: number; pixelHeight: number; displayMode: ImageDisplayMode; format: string; data: Uint8Array }
  | { tag: "TitleChanged"; paneId: bigint; title: string }
  | { tag: "ImageDeleted"; paneId: bigint }
  | { tag: "SessionInfoReply"; info: SessionDetailInfo }
  | { tag: "PaneListReply"; panes: (PaneDetailInfo)[] }
  | { tag: "CommandResult"; success: boolean; message: string; paneId: (bigint | null) }
  | { tag: "LayoutReply"; layout: LayoutState; sessionName: string }
  | { tag: "TemplateApplied"; sessionName: string }
  | { tag: "TemplateList"; templates: (TemplateInfo)[] }
  | { tag: "TemplateSaved"; templateName: string }
  | { tag: "BounceEdge"; direction: BounceDirection }
  | { tag: "Pong"; seq: bigint; clientTimeUs: bigint }
  | { tag: "PaneCapture"; sessionName: string; paneId: bigint; text: string; truncated: boolean }
  | { tag: "PromptListReply"; sessionName: string; paneId: bigint; marks: (PromptMarkInfo)[] }
  | { tag: "SetScrollOffset"; paneId: bigint; offset: number };

export interface SessionDetailInfo {
  name: string;
  running: boolean;
  paneCount: bigint;
  clientCount: bigint;
  workspaceCount: bigint;
  activeWorkspace: bigint;
}

export interface SessionInfo {
  name: string;
  running: boolean;
  paneCount: bigint;
  clientCount: bigint;
}

export interface TemplateInfo {
  name: string;
  description: (string | null);
  workspaceCount: bigint;
  totalPanes: bigint;
}

export interface TileState {
  paneId: bigint;
  weight: number;
}

export interface WorkspaceState {
  columns: (ColumnState)[];
  activeColumnIdx: bigint;
}

