//! Emit the schema / TS type definitions / round-trip fixtures the
//! `@loom/client` package needs to encode `ClientMessage` and decode
//! `ServerMessage` from msgpack bytes.
//!
//! Takes one argument — `schema`, `types`, or `fixtures` — and writes
//! the corresponding file to stdout. This mirrors `dump_constants` and
//! lets the cross-platform `web/scripts/gen.mjs` redirect each call
//! into the right output path.
//!
//! ```sh
//! cargo run -p loom-protocol --example dump_messages -- schema   > schema.ts
//! cargo run -p loom-protocol --example dump_messages -- types    > types.ts
//! cargo run -p loom-protocol --example dump_messages -- fixtures > fixtures.ts
//! ```
//!
//! The schema/types are derived from `serde-reflection::Tracer`, which
//! introspects the actual `Serialize` / `Deserialize` impls — so any
//! change to a `ClientMessage` / `ServerMessage` variant or to a nested
//! struct (LayoutState, SessionInfo, etc.) is picked up automatically.
//! The fixtures are built by hand from a curated list of representative
//! variants; encoding goes through the real `rmp_serde::to_vec`, which
//! is the same writer the server uses, so the hex bytes are the
//! authoritative wire-format ground truth for the TS round-trip tests.

use loom_protocol::codec::{
    ClientHello, SERVER_HELLO_LEN, WIRE_PROTOCOL_VERSION, build_client_hello,
};
use loom_protocol::message::*;
use serde::Serialize;
use serde_reflection::{ContainerFormat, Format, Named, Tracer, TracerConfig, VariantFormat};
use std::collections::BTreeMap;
use std::io::Write;

fn main() {
    let which = std::env::args().nth(1).unwrap_or_default();

    let mut tracer = Tracer::new(TracerConfig::default());
    // The top-level message enums pull in every nested struct they
    // reference. The two free-floating unit-only enums
    // (`BounceDirection`, `ImageDisplayMode`) appear inside variants
    // but `trace_simple_type<ServerMessage>` only discovers them
    // one variant at a time, so explicitly trace them to satisfy
    // `Tracer::registry()`'s completeness check.
    tracer
        .trace_simple_type::<ClientMessage>()
        .expect("trace ClientMessage");
    tracer
        .trace_simple_type::<ServerMessage>()
        .expect("trace ServerMessage");
    tracer
        .trace_simple_type::<BounceDirection>()
        .expect("trace BounceDirection");
    tracer
        .trace_simple_type::<ImageDisplayMode>()
        .expect("trace ImageDisplayMode");
    let registry = tracer.registry().expect("registry complete");

    let payload = match which.as_str() {
        "schema" => emit_schema(&registry),
        "types" => emit_types(&registry),
        "fixtures" => emit_fixtures(),
        other => {
            eprintln!(
                "usage: dump_messages <schema|types|fixtures>; got {other:?}"
            );
            std::process::exit(2);
        }
    };
    // Write as raw bytes to bypass platform-specific stdout
    // line-ending translation (cmd.exe on Windows converts LF→CRLF in
    // text mode); pairing this with `gen.mjs`'s `encoding: "buffer"`
    // gives us byte-identical output across hosts.
    std::io::stdout()
        .write_all(payload.as_bytes())
        .expect("stdout");
}

// ─── Schema emitter ─────────────────────────────────────────────────

const AUTOGEN_HEADER: &str = "// AUTO-GENERATED by `cargo run -p loom-protocol --example dump_messages`.\n\
// Do not edit by hand. Regenerate after any change to ClientMessage,\n\
// ServerMessage, or a nested struct referenced by them.\n\n";

fn emit_schema(registry: &BTreeMap<String, ContainerFormat>) -> String {
    let mut out = String::new();
    out.push_str(AUTOGEN_HEADER);
    out.push_str(include_str!("../codegen_assets/schema_prelude.ts.in"));
    out.push_str("\nexport const REGISTRY: Record<string, ContainerSpec> = {\n");
    for (name, fmt) in registry {
        out.push_str(&format!("  {name}: "));
        out.push_str(&emit_container_spec(fmt));
        out.push_str(",\n");
    }
    out.push_str("};\n");
    out
}

fn emit_container_spec(fmt: &ContainerFormat) -> String {
    match fmt {
        ContainerFormat::UnitStruct => r#"{ kind: "unit-struct" }"#.to_string(),
        ContainerFormat::NewTypeStruct(inner) => {
            format!(r#"{{ kind: "newtype-struct", of: {} }}"#, emit_schema_type(inner))
        }
        ContainerFormat::TupleStruct(items) => {
            let inner: Vec<String> = items.iter().map(emit_schema_type).collect();
            format!(r#"{{ kind: "tuple-struct", of: [{}] }}"#, inner.join(", "))
        }
        ContainerFormat::Struct(fields) => {
            let mut s = String::from(r#"{ kind: "struct", fields: ["#);
            s.push('\n');
            for f in fields {
                s.push_str("    ");
                s.push_str(&emit_field_spec(f));
                s.push_str(",\n");
            }
            s.push_str("  ] }");
            s
        }
        ContainerFormat::Enum(variants) => {
            let mut s = String::from(r#"{ kind: "enum", variants: ["#);
            s.push('\n');
            for (ord, named) in variants {
                let inner = emit_variant_spec(named);
                s.push_str(&format!(
                    "    {{ name: {:?}, ordinal: {}, shape: {} }},\n",
                    named.name, ord, inner
                ));
            }
            s.push_str("  ] }");
            s
        }
    }
}

fn emit_field_spec(field: &Named<Format>) -> String {
    let snake = &field.name;
    let camel = snake_to_camel(snake);
    let ty = emit_schema_type(&field.value);
    format!(
        r#"{{ name: {snake:?}, jsName: {camel:?}, type: {ty} }}"#,
        snake = snake,
        camel = camel,
    )
}

fn emit_variant_spec(named: &Named<VariantFormat>) -> String {
    match &named.value {
        VariantFormat::Unit => r#"{ kind: "unit-struct" }"#.to_string(),
        VariantFormat::NewType(inner) => format!(
            r#"{{ kind: "newtype-struct", of: {} }}"#,
            emit_schema_type(inner)
        ),
        VariantFormat::Tuple(items) => {
            let inner: Vec<String> = items.iter().map(emit_schema_type).collect();
            format!(r#"{{ kind: "tuple-struct", of: [{}] }}"#, inner.join(", "))
        }
        VariantFormat::Struct(fields) => {
            let mut s = String::from(r#"{ kind: "struct", fields: ["#);
            for f in fields {
                s.push_str(&emit_field_spec(f));
                s.push_str(", ");
            }
            s.push_str("] }");
            s
        }
        VariantFormat::Variable(_) => unreachable!("Variable should not survive registry()"),
    }
}

fn emit_schema_type(fmt: &Format) -> String {
    match fmt {
        Format::Unit => r#"{ kind: "unit" }"#.into(),
        Format::Bool => r#"{ kind: "bool" }"#.into(),
        Format::I8 => r#"{ kind: "i8" }"#.into(),
        Format::I16 => r#"{ kind: "i16" }"#.into(),
        Format::I32 => r#"{ kind: "i32" }"#.into(),
        Format::I64 => r#"{ kind: "i64" }"#.into(),
        Format::I128 => r#"{ kind: "i128" }"#.into(),
        Format::U8 => r#"{ kind: "u8" }"#.into(),
        Format::U16 => r#"{ kind: "u16" }"#.into(),
        Format::U32 => r#"{ kind: "u32" }"#.into(),
        Format::U64 => r#"{ kind: "u64" }"#.into(),
        Format::U128 => r#"{ kind: "u128" }"#.into(),
        Format::F32 => r#"{ kind: "f32" }"#.into(),
        Format::F64 => r#"{ kind: "f64" }"#.into(),
        Format::Char => r#"{ kind: "char" }"#.into(),
        Format::Str => r#"{ kind: "str" }"#.into(),
        Format::Bytes => r#"{ kind: "bytes" }"#.into(),
        Format::TypeName(n) => format!(r#"{{ kind: "ref", name: {n:?} }}"#),
        Format::Option(inner) => format!(r#"{{ kind: "option", of: {} }}"#, emit_schema_type(inner)),
        Format::Seq(inner) => format!(r#"{{ kind: "seq", of: {} }}"#, emit_schema_type(inner)),
        Format::Tuple(items) => {
            let inner: Vec<String> = items.iter().map(emit_schema_type).collect();
            format!(r#"{{ kind: "tuple", of: [{}] }}"#, inner.join(", "))
        }
        Format::TupleArray { content, size } => format!(
            r#"{{ kind: "tuple-array", of: {}, size: {} }}"#,
            emit_schema_type(content),
            size
        ),
        Format::Map { key, value } => format!(
            r#"{{ kind: "map", key: {}, value: {} }}"#,
            emit_schema_type(key),
            emit_schema_type(value)
        ),
        Format::Variable(_) => unreachable!("Variable should not survive registry()"),
    }
}

// ─── TS type emitter ────────────────────────────────────────────────

fn emit_types(registry: &BTreeMap<String, ContainerFormat>) -> String {
    let mut out = String::new();
    out.push_str(AUTOGEN_HEADER);
    out.push_str(
        "// Compile-time TypeScript shapes that mirror the wire format.\n\
         //   * `u64` / `i64` / `usize` are `bigint` (msgpack values may\n\
         //     exceed `Number.MAX_SAFE_INTEGER`).\n\
         //   * `Vec<u8>` fields are `Uint8Array` — the codec converts\n\
         //     to/from the msgpack `[u8]` array shape automatically.\n\
         //   * `Option<T>` is `T | null` (msgpack `nil` decodes as `null`).\n\n",
    );

    for (name, fmt) in registry {
        emit_type_decl(&mut out, name, fmt);
        out.push('\n');
    }
    out
}

fn emit_type_decl(out: &mut String, name: &str, fmt: &ContainerFormat) {
    match fmt {
        ContainerFormat::UnitStruct => {
            out.push_str(&format!("export type {name} = Record<string, never>;\n"));
        }
        ContainerFormat::NewTypeStruct(inner) => {
            out.push_str(&format!("export type {name} = {};\n", emit_ts_type(inner)));
        }
        ContainerFormat::TupleStruct(items) => {
            let inner: Vec<String> = items.iter().map(emit_ts_type).collect();
            out.push_str(&format!("export type {name} = [{}];\n", inner.join(", ")));
        }
        ContainerFormat::Struct(fields) => {
            out.push_str(&format!("export interface {name} {{\n"));
            for f in fields {
                out.push_str(&format!(
                    "  {}: {};\n",
                    snake_to_camel(&f.name),
                    emit_ts_type(&f.value)
                ));
            }
            out.push_str("}\n");
        }
        ContainerFormat::Enum(variants) => {
            out.push_str(&format!("export type {name} =\n"));
            for (i, (_ord, named)) in variants.iter().enumerate() {
                out.push_str("  | ");
                out.push_str(&emit_variant_ts(&named.name, &named.value));
                if i + 1 == variants.len() {
                    out.push(';');
                }
                out.push('\n');
            }
        }
    }
}

fn emit_variant_ts(name: &str, vf: &VariantFormat) -> String {
    match vf {
        VariantFormat::Unit => format!(r#"{{ tag: "{name}" }}"#),
        VariantFormat::NewType(inner) => {
            format!(r#"{{ tag: "{name}"; value: {} }}"#, emit_ts_type(inner))
        }
        VariantFormat::Tuple(items) => {
            let inner: Vec<String> = items.iter().map(emit_ts_type).collect();
            format!(r#"{{ tag: "{name}"; value: [{}] }}"#, inner.join(", "))
        }
        VariantFormat::Struct(fields) => {
            let mut s = format!(r#"{{ tag: "{name}""#);
            for f in fields {
                s.push_str(&format!(
                    "; {}: {}",
                    snake_to_camel(&f.name),
                    emit_ts_type(&f.value)
                ));
            }
            s.push_str(" }");
            s
        }
        VariantFormat::Variable(_) => unreachable!(),
    }
}

fn emit_ts_type(fmt: &Format) -> String {
    match fmt {
        Format::Unit => "null".into(),
        Format::Bool => "boolean".into(),
        Format::I8 | Format::I16 | Format::I32 => "number".into(),
        Format::I64 | Format::I128 => "bigint".into(),
        Format::U8 | Format::U16 | Format::U32 => "number".into(),
        // usize and u64 collapse to `U64` in the wire format; both are bigint on the JS side.
        Format::U64 | Format::U128 => "bigint".into(),
        Format::F32 | Format::F64 => "number".into(),
        Format::Char => "string".into(),
        Format::Str => "string".into(),
        Format::Bytes => "Uint8Array".into(),
        Format::TypeName(n) => n.clone(),
        Format::Option(inner) => format!("({} | null)", emit_ts_type(inner)),
        Format::Seq(inner) => match inner.as_ref() {
            // `Vec<u8>` on the JS side is more useful as a Uint8Array,
            // even though the wire shape is a fixarray of u8s.
            Format::U8 => "Uint8Array".into(),
            other => format!("({})[]", emit_ts_type(other)),
        },
        Format::Tuple(items) => {
            let inner: Vec<String> = items.iter().map(emit_ts_type).collect();
            format!("[{}]", inner.join(", "))
        }
        Format::TupleArray { content, size } => {
            let inner = emit_ts_type(content);
            // Spread as fixed-length tuple `[T, T, ..., T]` — sound but
            // verbose for large N; the only N's we currently see are
            // small (e.g. RGBA = 4).
            let parts = (0..*size).map(|_| inner.clone()).collect::<Vec<_>>();
            format!("[{}]", parts.join(", "))
        }
        Format::Map { key, value } => format!(
            "Map<{}, {}>",
            emit_ts_type(key),
            emit_ts_type(value)
        ),
        Format::Variable(_) => unreachable!(),
    }
}

// ─── Fixture emitter ────────────────────────────────────────────────

fn emit_fixtures() -> String {
    let mut out = String::new();
    out.push_str(AUTOGEN_HEADER);
    out.push_str(
        "// Curated round-trip fixtures: one representative of each \
         shape\n// (unit variant, primitive-only struct, optional \
         field, nested struct,\n// byte payload, named-enum subfield, \
         etc.). Hex bytes come from\n// `rmp_serde::to_vec` — the same \
         encoder the server uses — so any\n// future wire-format \
         change shows up as a fixture diff.\n\n",
    );
    out.push_str("import type { ClientMessage, ServerMessage } from \"./types.js\";\n\n");
    out.push_str("export interface Fixture<T> { name: string; hex: string; value: T; }\n\n");

    out.push_str("// ── Handshake fixtures ────────────────────────────────\n");
    out.push_str(&format!(
        "export const WIRE_PROTOCOL_VERSION = {WIRE_PROTOCOL_VERSION};\n"
    ));
    out.push_str(&format!(
        "export const SERVER_HELLO_LEN = {SERVER_HELLO_LEN};\n"
    ));
    // Mirror `handshake::parse_pkg_version`: pack major.minor.patch
    // (8/8/16 bits) of the loom-protocol crate at codegen time. The
    // server compares this byte-identical value during ClientHello,
    // so emitting it from Rust avoids drift on workspace bumps.
    let pkg_version = encode_pkg_version(env!("CARGO_PKG_VERSION"));
    out.push_str(
        "/** Packed semver (major<<24 | minor<<16 | patch) of loom-protocol at codegen time. */\n",
    );
    out.push_str(&format!(
        "export const LOOM_PKG_VERSION = 0x{pkg_version:08x};\n\n"
    ));
    out.push_str("export interface HelloFixture {\n");
    out.push_str("  name: string;\n");
    out.push_str("  hex: string;\n");
    out.push_str("  hello: {\n");
    out.push_str("    sessionName: string;\n");
    out.push_str("    width: number;\n");
    out.push_str("    height: number;\n");
    out.push_str("    cellWidth: number;\n");
    out.push_str("    cellHeight: number;\n");
    out.push_str("  };\n");
    out.push_str("}\n\n");
    out.push_str("export const HELLO_FIXTURES: HelloFixture[] = [\n");
    for h in hello_fixtures() {
        let bytes = build_client_hello(&h).expect("build_client_hello");
        out.push_str(&format!(
            "  {{ name: {:?}, hex: {:?}, hello: {{ sessionName: {:?}, width: {}, height: {}, cellWidth: {:?}, cellHeight: {:?} }} }},\n",
            h.session_name,
            hex(&bytes),
            h.session_name,
            h.width,
            h.height,
            h.cell_width,
            h.cell_height,
        ));
    }
    out.push_str("];\n\n");

    let client = client_fixtures();
    let server = server_fixtures();

    out.push_str("export const CLIENT_FIXTURES: Fixture<ClientMessage>[] = [\n");
    for (name, hex, ts_lit) in client {
        out.push_str(&format!(
            "  {{ name: {:?}, hex: {:?}, value: {} }},\n",
            name, hex, ts_lit
        ));
    }
    out.push_str("];\n\n");

    out.push_str("export const SERVER_FIXTURES: Fixture<ServerMessage>[] = [\n");
    for (name, hex, ts_lit) in server {
        out.push_str(&format!(
            "  {{ name: {:?}, hex: {:?}, value: {} }},\n",
            name, hex, ts_lit
        ));
    }
    out.push_str("];\n");
    out
}

/// Each entry is `(human-readable name, hex(rmp_serde::to_vec(msg)), TS literal expression)`.
/// The TS literal is what the decoder must produce and what the
/// encoder must accept; it's evaluated in `fixtures.ts` and therefore
/// must use only `ClientMessage`-typed shapes.
fn client_fixtures() -> Vec<(&'static str, String, String)> {
    let cases: Vec<(&'static str, ClientMessage, &'static str)> = vec![
        (
            "Input bytes",
            ClientMessage::Input {
                pane_id: 42,
                data: vec![0x61, 0x62, 0x63],
                input_seq: 7,
            },
            r#"{ tag: "Input", paneId: 42n, data: new Uint8Array([0x61, 0x62, 0x63]), inputSeq: 7n }"#,
        ),
        (
            "Ack u64",
            ClientMessage::Ack { generation: 12345 },
            r#"{ tag: "Ack", generation: 12345n }"#,
        ),
        (
            "Attach (unit)",
            ClientMessage::Attach,
            r#"{ tag: "Attach" }"#,
        ),
        (
            "Resize floats",
            ClientMessage::Resize {
                cols: 80,
                rows: 24,
                width: 1280,
                height: 720,
                cell_width: 9.5,
                cell_height: 18.0,
            },
            r#"{ tag: "Resize", cols: 80, rows: 24, width: 1280, height: 720, cellWidth: 9.5, cellHeight: 18.0 }"#,
        ),
        (
            "SetColumnWidth (Some)",
            ClientMessage::SetColumnWidth {
                proportion: 0.5,
                fixed_px: Some(320.0),
            },
            r#"{ tag: "SetColumnWidth", proportion: 0.5, fixedPx: 320.0 }"#,
        ),
        (
            "SetColumnWidth (None)",
            ClientMessage::SetColumnWidth {
                proportion: 0.75,
                fixed_px: None,
            },
            r#"{ tag: "SetColumnWidth", proportion: 0.75, fixedPx: null }"#,
        ),
        (
            "MouseInput (bool + bytes)",
            ClientMessage::MouseInput {
                pane_id: 7,
                button: 0,
                col: 12,
                row: 5,
                pressed: true,
                modifiers: 4,
            },
            r#"{ tag: "MouseInput", paneId: 7n, button: 0, col: 12, row: 5, pressed: true, modifiers: 4 }"#,
        ),
        (
            "Ping u64s",
            ClientMessage::Ping {
                seq: 9,
                client_time_us: 1_700_000_000_000_000,
            },
            r#"{ tag: "Ping", seq: 9n, clientTimeUs: 1700000000000000n }"#,
        ),
        (
            "RunCommand (string + Option<string>)",
            ClientMessage::RunCommand {
                session_name: "main".into(),
                command: "ls -la".into(),
                cwd: Some("/home/u".into()),
            },
            r#"{ tag: "RunCommand", sessionName: "main", command: "ls -la", cwd: "/home/u" }"#,
        ),
    ];

    cases
        .into_iter()
        .map(|(name, msg, ts_lit)| (name, hex(&rmp_to_vec(&msg)), ts_lit.into()))
        .collect()
}

fn server_fixtures() -> Vec<(&'static str, String, String)> {
    let cases: Vec<(&'static str, ServerMessage, &'static str)> = vec![
        (
            "Bell",
            ServerMessage::Bell { pane_id: 9 },
            r#"{ tag: "Bell", paneId: 9n }"#,
        ),
        (
            "ServerShutdown (unit)",
            ServerMessage::ServerShutdown,
            r#"{ tag: "ServerShutdown" }"#,
        ),
        (
            "Error (string)",
            ServerMessage::Error {
                message: "boom".into(),
            },
            r#"{ tag: "Error", message: "boom" }"#,
        ),
        (
            "Pong u64",
            ServerMessage::Pong {
                seq: 3,
                client_time_us: 42,
            },
            r#"{ tag: "Pong", seq: 3n, clientTimeUs: 42n }"#,
        ),
        (
            "PaneCreated nested ints",
            ServerMessage::PaneCreated {
                pane_id: 1,
                column_idx: 0,
                cols: 80,
                rows: 24,
            },
            r#"{ tag: "PaneCreated", paneId: 1n, columnIdx: 0n, cols: 80, rows: 24 }"#,
        ),
        (
            "SessionList nested struct",
            ServerMessage::SessionList {
                sessions: vec![
                    SessionInfo {
                        name: "main".into(),
                        running: true,
                        pane_count: 3,
                        client_count: 1,
                    },
                    SessionInfo {
                        name: "saved".into(),
                        running: false,
                        pane_count: 0,
                        client_count: 0,
                    },
                ],
            },
            r#"{ tag: "SessionList", sessions: [
              { name: "main", running: true, paneCount: 3n, clientCount: 1n },
              { name: "saved", running: false, paneCount: 0n, clientCount: 0n },
            ] }"#,
        ),
        (
            "BounceEdge nested unit-enum",
            ServerMessage::BounceEdge {
                direction: BounceDirection::Left,
            },
            r#"{ tag: "BounceEdge", direction: { tag: "Left" } }"#,
        ),
        (
            "StateSync layout tree",
            ServerMessage::StateSync {
                layout: LayoutState {
                    workspaces: vec![WorkspaceState {
                        columns: vec![ColumnState {
                            tiles: vec![TileState {
                                pane_id: 1,
                                weight: 1.0,
                            }],
                            active_tile_idx: 0,
                            width_proportion: 1.0,
                            width_fixed_px: None,
                        }],
                        active_column_idx: 0,
                    }],
                    active_workspace_idx: 0,
                },
                pane_ids: vec![1, 2],
            },
            r#"{ tag: "StateSync", layout: {
              workspaces: [{
                columns: [{
                  tiles: [{ paneId: 1n, weight: 1.0 }],
                  activeTileIdx: 0n,
                  widthProportion: 1.0,
                  widthFixedPx: null,
                }],
                activeColumnIdx: 0n,
              }],
              activeWorkspaceIdx: 0n,
            }, paneIds: [1n, 2n] }"#,
        ),
    ];
    cases
        .into_iter()
        .map(|(name, msg, ts_lit)| (name, hex(&rmp_to_vec(&msg)), ts_lit.into()))
        .collect()
}

fn encode_pkg_version(v: &str) -> u32 {
    let parts: Vec<&str> = v.split('.').collect();
    assert_eq!(parts.len(), 3, "CARGO_PKG_VERSION must be major.minor.patch");
    let major: u32 = parts[0].parse().unwrap();
    let minor: u32 = parts[1].parse().unwrap();
    let patch: u32 = parts[2].parse().unwrap();
    (major << 24) | (minor << 16) | patch
}

fn hello_fixtures() -> Vec<ClientHello> {
    // All fixtures must satisfy `loom_session::names::validate_name`
    // — the server runs it before sending ServerHello and the TS
    // `validateClientHello` mirrors it. Earlier drafts included an
    // empty session name and a multi-byte UTF-8 name to stress the
    // length-prefix encoding; both are rejected by the validator, so
    // the wire-shape tests for them never reach the real handshake.
    vec![
        ClientHello {
            session_name: "main".into(),
            width: 1280,
            height: 720,
            cell_width: 9.5,
            cell_height: 18.0,
        },
        ClientHello {
            // 64-char name: max length, exercises the upper bound.
            session_name: "a".repeat(64),
            width: 800,
            height: 600,
            cell_width: 10.0,
            cell_height: 20.0,
        },
        ClientHello {
            // Digits + hyphen + lowercase: a "session-like" name from
            // `random_name()` style generators.
            session_name: "fresh-fox-12".into(),
            width: 1920,
            height: 1080,
            cell_width: 8.0,
            cell_height: 16.0,
        },
    ]
}

fn rmp_to_vec<T: Serialize + ?Sized>(value: &T) -> Vec<u8> {
    rmp_serde::to_vec(value).expect("encode")
}

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

// ─── Naming helpers ─────────────────────────────────────────────────

fn snake_to_camel(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper_next = false;
    for c in s.chars() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            for u in c.to_uppercase() {
                out.push(u);
            }
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}
