[package]
name = "ciri"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ciri"
path = "src/main.rs"

[dependencies]
ciri-render = { workspace = true }
ciri-gpu = { workspace = true }
ciri-protocol = { workspace = true }
ciri-session = { path = "../ciri-session" }
ciri-layout = { path = "../ciri-layout" }
ciri-anim = { path = "../ciri-anim" }
ciri-input = { path = "../ciri-input" }
ciri-config = { workspace = true }
crossbeam-channel = { workspace = true }
rmp-serde = { workspace = true }
winit = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
serde_json = "1"
arboard = { workspace = true }
notify = { workspace = true }
libc = { workspace = true }
