// AUTO-GENERATED by `cargo run -p ciri-protocol --example dump_constants`.
// Do not edit by hand. Regenerate after touching the Rust constants.

// ── Handshake / framing ───────────────────────────────
export const WIRE_PROTOCOL_VERSION = 4;
export const SERVER_HELLO_LEN = 8;
export const MAX_DATA_FRAME_LEN = 16777216;
export const MAX_CONTROL_FRAME_LEN = 1048576;

// Frame tag bytes (server → client + client → server).
export const TAG_CLIENT_MSG = 0x01;
export const TAG_SERVER_MSG = 0x10;
export const TAG_CELL_DELTA = 0x20;
export const TAG_FULL_PANE_SYNC = 0x21;
export const TAG_CELL_DELTA_LZ4 = 0x22;
export const TAG_FULL_PANE_SYNC_LZ4 = 0x23;

// ── PackedCell layout ─────────────────────────────────
export const PACKED_CELL_SIZE = 16;
export const DEFAULT_CELL_CHAR = 0x20; // space
export const DEFAULT_CELL_FLAGS = 0x0000;

// ── Color discriminant tags ───────────────────────────
export const COLOR_NAMED = 0;
export const COLOR_RGB = 1;
export const COLOR_INDEXED = 2;

// ── Named color IDs ───────────────────────────────────
export const NAMED_BLACK = 0;
export const NAMED_RED = 1;
export const NAMED_GREEN = 2;
export const NAMED_YELLOW = 3;
export const NAMED_BLUE = 4;
export const NAMED_MAGENTA = 5;
export const NAMED_CYAN = 6;
export const NAMED_WHITE = 7;
export const NAMED_BRIGHT_BLACK = 8;
export const NAMED_BRIGHT_RED = 9;
export const NAMED_BRIGHT_GREEN = 10;
export const NAMED_BRIGHT_YELLOW = 11;
export const NAMED_BRIGHT_BLUE = 12;
export const NAMED_BRIGHT_MAGENTA = 13;
export const NAMED_BRIGHT_CYAN = 14;
export const NAMED_BRIGHT_WHITE = 15;
export const NAMED_FOREGROUND = 16;
export const NAMED_BACKGROUND = 17;
export const NAMED_CURSOR = 18;
export const NAMED_DIM_BLACK = 19;
export const NAMED_DIM_RED = 20;
export const NAMED_DIM_GREEN = 21;
export const NAMED_DIM_YELLOW = 22;
export const NAMED_DIM_BLUE = 23;
export const NAMED_DIM_MAGENTA = 24;
export const NAMED_DIM_CYAN = 25;
export const NAMED_DIM_WHITE = 26;
export const NAMED_BRIGHT_FOREGROUND = 27;
export const NAMED_DIM_FOREGROUND = 28;

// ── Cell flag bits ────────────────────────────────────
export const FLAG_WIDE_CHAR = 0x0001;
export const FLAG_WIDE_CHAR_SPACER = 0x0002;
export const FLAG_BOLD = 0x0004;
export const FLAG_ITALIC = 0x0008;
export const FLAG_UNDERLINE = 0x0010;
export const FLAG_INVERSE = 0x0020;
export const FLAG_DIM = 0x0040;
export const FLAG_STRIKEOUT = 0x0080;
export const FLAG_HIDDEN = 0x0100;
export const FLAG_UNDERLINE_STYLE_MASK = 0x0e00;
export const FLAG_UNDERLINE_DOUBLE = 0x0200;
export const FLAG_UNDERLINE_CURLY = 0x0400;
export const FLAG_UNDERLINE_DOTTED = 0x0600;
export const FLAG_UNDERLINE_DASHED = 0x0800;
export const FLAG_WRAPLINE = 0x1000;
export const FLAG_HYPERLINK = 0x2000;

// ── Terminal mode flags ───────────────────────────────
export const MODE_MOUSE_REPORT = 0x0001;
export const MODE_ALT_SCREEN = 0x0002;
export const MODE_SHELL_INTEGRATION = 0x0004;
export const MODE_KITTY_KEYBOARD = 0x0008;
export const MODE_BRACKETED_PASTE = 0x0010;
export const MODE_FOCUS_EVENT = 0x0020;
export const MODE_SYNCHRONIZED_OUTPUT = 0x0040;
export const MODE_KITTY_REPORT_EVENTS = 0x0100;
export const MODE_KITTY_REPORT_ALTERNATES = 0x0200;
export const MODE_KITTY_REPORT_ALL = 0x0400;
export const MODE_KITTY_REPORT_TEXT = 0x0800;
export const MODE_PASSWORD_INPUT = 0x1000;
export const MODE_APP_CURSOR = 0x2000;
export const MODE_APP_KEYPAD = 0x4000;
export const MODE_ALTERNATE_SCROLL = 0x8000;
export const MODE_KITTY_ALL = 0x0f08;

// ── Cursor shape ──────────────────────────────────────
export const CURSOR_BLOCK = 0;
export const CURSOR_UNDERLINE = 1;
export const CURSOR_BEAM = 2;
export const CURSOR_HIDDEN = 3;
export const CURSOR_HOLLOW_BLOCK = 4;

// ── State-machine cell opcodes ────────────────────────
export const OP_SET_FG = 0x01;
export const OP_SET_BG = 0x02;
export const OP_SET_FLAGS = 0x03;
export const OP_SET_FG_BG = 0x04;
export const OP_RESET = 0x05;
export const OP_SET_FG_NAMED = 0x06;
export const OP_SET_BG_NAMED = 0x07;
export const OP_SET_FG_INDEXED = 0x08;
export const OP_SET_BG_INDEXED = 0x09;
export const OP_CHAR1 = 0x10;
export const OP_CHARS = 0x11;
export const OP_REPEAT = 0x12;
export const OP_CHARS_LONG = 0x13;
export const OP_ASCII = 0x14;
export const OP_ASCII_REPEAT = 0x15;
export const OP_END = 0xff;
