[package]
name = "ciri-render"
version.workspace = true
edition.workspace = true

[dependencies]
crossfont = { workspace = true }
fontdb = { workspace = true }
winit = { workspace = true }
alacritty_terminal = { workspace = true }
ciri-protocol = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
bytemuck = { version = "1", features = ["derive"] }
bytemuck_derive = "1"
freetype-rs = { workspace = true }
ciri-config = { path = "../ciri-config" }
rustybuzz = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = "0.2"
unicode-properties = "0.1"
ttf-parser = "0.24"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Foundation",
    "implement",
] }
windows-core = "0.58"

[dev-dependencies]
ciri-app = { workspace = true }
