[package]
name = "ciri-render"
version.workspace = true
edition.workspace = true

[dependencies]
crossfont = { workspace = true }
fontdb = { workspace = true }
winit = { workspace = true }
alacritty_terminal = { workspace = true }
ciri-protocol = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
bytemuck = { version = "1", features = ["derive"] }
bytemuck_derive = "1"
freetype-rs = { workspace = true }
ciri-config = { path = "../ciri-config" }
rustybuzz = { workspace = true }
unicode-segmentation = { workspace = true }
