// AUTO-GENERATED by `cargo run -p loom-protocol --example dump_messages`.
// Do not edit by hand. Regenerate after any change to ClientMessage,
// ServerMessage, or a nested struct referenced by them.

// Curated round-trip fixtures: one representative of each shape
// (unit variant, primitive-only struct, optional field, nested struct,
// byte payload, named-enum subfield, etc.). Hex bytes come from
// `rmp_serde::to_vec` — the same encoder the server uses — so any
// future wire-format change shows up as a fixture diff.

import type { ClientMessage, ServerMessage } from "./types.js";

export interface Fixture<T> { name: string; hex: string; value: T; }

// ── Handshake fixtures ────────────────────────────────
export const WIRE_PROTOCOL_VERSION = 1;
export const SERVER_HELLO_LEN = 8;
/** Packed semver (major<<24 | minor<<16 | patch) of loom-protocol at codegen time. */
export const LOOM_PKG_VERSION = 0x00010000;

export interface HelloFixture {
  name: string;
  hex: string;
  hello: {
    sessionName: string;
    width: number;
    height: number;
    cellWidth: number;
    cellHeight: number;
  };
}

export const HELLO_FIXTURES: HelloFixture[] = [
  { name: "main", hex: "4c4f4f4d000001000104006d61696e00050000d00200000000184100009041", hello: { sessionName: "main", width: 1280, height: 720, cellWidth: 9.5, cellHeight: 18.0 } },
  { name: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", hex: "4c4f4f4d00000100014000616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161612003000058020000000020410000a041", hello: { sessionName: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", width: 800, height: 600, cellWidth: 10.0, cellHeight: 20.0 } },
  { name: "fresh-fox-12", hex: "4c4f4f4d00000100010c0066726573682d666f782d313280070000380400000000004100008041", hello: { sessionName: "fresh-fox-12", width: 1920, height: 1080, cellWidth: 8.0, cellHeight: 16.0 } },
];

export const CLIENT_FIXTURES: Fixture<ClientMessage>[] = [
  { name: "Input bytes", hex: "81a5496e707574932a9361626307", value: { tag: "Input", paneId: 42n, data: new Uint8Array([0x61, 0x62, 0x63]), inputSeq: 7n } },
  { name: "Ack u64", hex: "81a341636b91cd3039", value: { tag: "Ack", generation: 12345n } },
  { name: "Attach (unit)", hex: "a6417474616368", value: { tag: "Attach" } },
  { name: "Resize floats", hex: "81a6526573697a65965018cd0500cd02d0ca41180000ca41900000", value: { tag: "Resize", cols: 80, rows: 24, width: 1280, height: 720, cellWidth: 9.5, cellHeight: 18.0 } },
  { name: "SetColumnWidth (Some)", hex: "81ae536574436f6c756d6e576964746892cb3fe0000000000000cb4074000000000000", value: { tag: "SetColumnWidth", proportion: 0.5, fixedPx: 320.0 } },
  { name: "SetColumnWidth (None)", hex: "81ae536574436f6c756d6e576964746892cb3fe8000000000000c0", value: { tag: "SetColumnWidth", proportion: 0.75, fixedPx: null } },
  { name: "MouseInput (bool + bytes)", hex: "81aa4d6f757365496e7075749607000c05c304", value: { tag: "MouseInput", paneId: 7n, button: 0, col: 12, row: 5, pressed: true, modifiers: 4 } },
  { name: "Ping u64s", hex: "81a450696e679209cf00060a24181e4000", value: { tag: "Ping", seq: 9n, clientTimeUs: 1700000000000000n } },
  { name: "RunCommand (string + Option<string>)", hex: "81aa52756e436f6d6d616e6494a46d61696ea66c73202d6c61a72f686f6d652f75c2", value: { tag: "RunCommand", sessionName: "main", command: "ls -la", cwd: "/home/u" } },
];

export const SERVER_FIXTURES: Fixture<ServerMessage>[] = [
  { name: "Bell", hex: "81a442656c6c9109", value: { tag: "Bell", paneId: 9n } },
  { name: "ServerShutdown (unit)", hex: "ae53657276657253687574646f776e", value: { tag: "ServerShutdown" } },
  { name: "Error (string)", hex: "81a54572726f7291a4626f6f6d", value: { tag: "Error", message: "boom" } },
  { name: "Pong u64", hex: "81a4506f6e6792032a", value: { tag: "Pong", seq: 3n, clientTimeUs: 42n } },
  { name: "PaneCreated nested ints", hex: "81ab50616e65437265617465649401005018", value: { tag: "PaneCreated", paneId: 1n, columnIdx: 0n, cols: 80, rows: 24 } },
  { name: "SessionList nested struct", hex: "81ab53657373696f6e4c697374919294a46d61696ec3030194a57361766564c20000", value: { tag: "SessionList", sessions: [
              { name: "main", running: true, paneCount: 3n, clientCount: 1n },
              { name: "saved", running: false, paneCount: 0n, clientCount: 0n },
            ] } },
  { name: "BounceEdge nested unit-enum", hex: "81aa426f756e63654564676591a44c656674", value: { tag: "BounceEdge", direction: { tag: "Left" } } },
  { name: "StateSync layout tree", hex: "81a9537461746553796e63929291929194919201ca3f80000000cb3ff0000000000000c00000920102", value: { tag: "StateSync", layout: {
              workspaces: [{
                columns: [{
                  tiles: [{ paneId: 1n, weight: 1.0 }],
                  activeTileIdx: 0n,
                  widthProportion: 1.0,
                  widthFixedPx: null,
                }],
                activeColumnIdx: 0n,
              }],
              activeWorkspaceIdx: 0n,
            }, paneIds: [1n, 2n] } },
];
