// AUTO-GENERATED by `cargo run -p loom-protocol --example dump_messages`.
// Do not edit by hand. Regenerate after any change to ClientMessage,
// ServerMessage, or a nested struct referenced by them.

// Runtime schema describing how to encode/decode ClientMessage,
// ServerMessage, and the structs they reference. The shape mirrors
// `serde_reflection::ContainerFormat` so the codec can stay generic
// and walk this tree at runtime.

/** Wire-format primitives + composite types. */
export type SchemaType =
  | { kind: "unit" }
  | { kind: "bool" }
  | { kind: "i8" } | { kind: "i16" } | { kind: "i32" } | { kind: "i64" } | { kind: "i128" }
  | { kind: "u8" } | { kind: "u16" } | { kind: "u32" } | { kind: "u64" } | { kind: "u128" }
  | { kind: "f32" } | { kind: "f64" }
  | { kind: "char" }
  | { kind: "str" }
  | { kind: "bytes" }
  | { kind: "ref"; name: string }
  | { kind: "option"; of: SchemaType }
  | { kind: "seq"; of: SchemaType }
  | { kind: "tuple"; of: SchemaType[] }
  | { kind: "tuple-array"; of: SchemaType; size: number }
  | { kind: "map"; key: SchemaType; value: SchemaType };

export interface FieldSpec {
  /** Wire name (snake_case, as serde sees it). Diagnostics only — the
   *  msgpack payload is a positional array, so we never read this
   *  name off the wire. */
  name: string;
  /** JS-side property name (camelCase). The codec uses this to map
   *  positional wire array elements to/from named TS objects. */
  jsName: string;
  type: SchemaType;
}

export interface VariantSpec {
  name: string;
  /** 0-based ordinal serde uses for this variant. Not on the wire for
   *  externally-tagged enums, but kept for diagnostics. */
  ordinal: number;
  shape: ContainerSpec;
}

export type ContainerSpec =
  | { kind: "unit-struct" }
  | { kind: "newtype-struct"; of: SchemaType }
  | { kind: "tuple-struct"; of: SchemaType[] }
  | { kind: "struct"; fields: FieldSpec[] }
  | { kind: "enum"; variants: VariantSpec[] };

export const REGISTRY: Record<string, ContainerSpec> = {
  BounceDirection: { kind: "enum", variants: [
    { name: "Left", ordinal: 0, shape: { kind: "unit-struct" } },
    { name: "Right", ordinal: 1, shape: { kind: "unit-struct" } },
    { name: "Up", ordinal: 2, shape: { kind: "unit-struct" } },
    { name: "Down", ordinal: 3, shape: { kind: "unit-struct" } },
  ] },
  CapturePaneOpts: { kind: "struct", fields: [
    { name: "scrollback_rows", jsName: "scrollbackRows", type: { kind: "u32" } },
    { name: "join_wrapped", jsName: "joinWrapped", type: { kind: "bool" } },
    { name: "preserve_trailing_spaces", jsName: "preserveTrailingSpaces", type: { kind: "bool" } },
  ] },
  ClientMessage: { kind: "enum", variants: [
    { name: "Input", ordinal: 0, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "data", jsName: "data", type: { kind: "seq", of: { kind: "u8" } } }, { name: "input_seq", jsName: "inputSeq", type: { kind: "u64" } }, ] } },
    { name: "CreatePane", ordinal: 1, shape: { kind: "unit-struct" } },
    { name: "SplitDown", ordinal: 2, shape: { kind: "unit-struct" } },
    { name: "NewTileBelow", ordinal: 3, shape: { kind: "unit-struct" } },
    { name: "ClosePane", ordinal: 4, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, ] } },
    { name: "FocusLeft", ordinal: 5, shape: { kind: "unit-struct" } },
    { name: "FocusRight", ordinal: 6, shape: { kind: "unit-struct" } },
    { name: "FocusUp", ordinal: 7, shape: { kind: "unit-struct" } },
    { name: "FocusDown", ordinal: 8, shape: { kind: "unit-struct" } },
    { name: "MovePaneLeft", ordinal: 9, shape: { kind: "unit-struct" } },
    { name: "MovePaneRight", ordinal: 10, shape: { kind: "unit-struct" } },
    { name: "MovePaneUp", ordinal: 11, shape: { kind: "unit-struct" } },
    { name: "MovePaneDown", ordinal: 12, shape: { kind: "unit-struct" } },
    { name: "Resize", ordinal: 13, shape: { kind: "struct", fields: [{ name: "cols", jsName: "cols", type: { kind: "u16" } }, { name: "rows", jsName: "rows", type: { kind: "u16" } }, { name: "width", jsName: "width", type: { kind: "u32" } }, { name: "height", jsName: "height", type: { kind: "u32" } }, { name: "cell_width", jsName: "cellWidth", type: { kind: "f32" } }, { name: "cell_height", jsName: "cellHeight", type: { kind: "f32" } }, ] } },
    { name: "SetColumnWidth", ordinal: 14, shape: { kind: "struct", fields: [{ name: "proportion", jsName: "proportion", type: { kind: "f64" } }, { name: "fixed_px", jsName: "fixedPx", type: { kind: "option", of: { kind: "f64" } } }, ] } },
    { name: "AdjustColumnSplit", ordinal: 15, shape: { kind: "struct", fields: [{ name: "delta", jsName: "delta", type: { kind: "f64" } }, ] } },
    { name: "EqualizeColumnSplit", ordinal: 16, shape: { kind: "unit-struct" } },
    { name: "Attach", ordinal: 17, shape: { kind: "unit-struct" } },
    { name: "Detach", ordinal: 18, shape: { kind: "unit-struct" } },
    { name: "Ack", ordinal: 19, shape: { kind: "struct", fields: [{ name: "generation", jsName: "generation", type: { kind: "u64" } }, ] } },
    { name: "MouseInput", ordinal: 20, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "button", jsName: "button", type: { kind: "u8" } }, { name: "col", jsName: "col", type: { kind: "u16" } }, { name: "row", jsName: "row", type: { kind: "u16" } }, { name: "pressed", jsName: "pressed", type: { kind: "bool" } }, { name: "modifiers", jsName: "modifiers", type: { kind: "u8" } }, ] } },
    { name: "SwitchWorkspace", ordinal: 21, shape: { kind: "struct", fields: [{ name: "workspace_idx", jsName: "workspaceIdx", type: { kind: "u64" } }, ] } },
    { name: "ConsumeIntoColumn", ordinal: 22, shape: { kind: "unit-struct" } },
    { name: "ExpelFromColumn", ordinal: 23, shape: { kind: "unit-struct" } },
    { name: "ListSessions", ordinal: 24, shape: { kind: "struct", fields: [{ name: "all", jsName: "all", type: { kind: "bool" } }, ] } },
    { name: "KillSession", ordinal: 25, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "KillServer", ordinal: 26, shape: { kind: "unit-struct" } },
    { name: "SwitchSession", ordinal: 27, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "SetTileWeights", ordinal: 28, shape: { kind: "struct", fields: [{ name: "column_idx", jsName: "columnIdx", type: { kind: "u64" } }, { name: "top_tile_idx", jsName: "topTileIdx", type: { kind: "u64" } }, { name: "top_weight", jsName: "topWeight", type: { kind: "f64" } }, { name: "bottom_weight", jsName: "bottomWeight", type: { kind: "f64" } }, ] } },
    { name: "AdjustColumnSplitAt", ordinal: 29, shape: { kind: "struct", fields: [{ name: "column_idx", jsName: "columnIdx", type: { kind: "u64" } }, { name: "delta", jsName: "delta", type: { kind: "f64" } }, ] } },
    { name: "FocusChange", ordinal: 30, shape: { kind: "struct", fields: [{ name: "focused", jsName: "focused", type: { kind: "bool" } }, ] } },
    { name: "FocusPane", ordinal: 31, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, ] } },
    { name: "SendKeys", ordinal: 32, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, { name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "keys", jsName: "keys", type: { kind: "seq", of: { kind: "u8" } } }, ] } },
    { name: "RunCommand", ordinal: 33, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, { name: "command", jsName: "command", type: { kind: "str" } }, { name: "cwd", jsName: "cwd", type: { kind: "option", of: { kind: "str" } } }, ] } },
    { name: "GetSessionInfo", ordinal: 34, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "ListPanes", ordinal: 35, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "FocusPaneById", ordinal: 36, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, { name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, ] } },
    { name: "ClosePaneById", ordinal: 37, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, { name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, ] } },
    { name: "CreatePaneIn", ordinal: 38, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "GetLayout", ordinal: 39, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "ApplyTemplate", ordinal: 40, shape: { kind: "struct", fields: [{ name: "template_name", jsName: "templateName", type: { kind: "str" } }, { name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "ListTemplates", ordinal: 41, shape: { kind: "unit-struct" } },
    { name: "SaveTemplate", ordinal: 42, shape: { kind: "struct", fields: [{ name: "template_name", jsName: "templateName", type: { kind: "str" } }, { name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "Ping", ordinal: 43, shape: { kind: "struct", fields: [{ name: "seq", jsName: "seq", type: { kind: "u64" } }, { name: "client_time_us", jsName: "clientTimeUs", type: { kind: "u64" } }, ] } },
    { name: "CapturePane", ordinal: 44, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, { name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "opts", jsName: "opts", type: { kind: "ref", name: "CapturePaneOpts" } }, ] } },
    { name: "ListPrompts", ordinal: 45, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, { name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, ] } },
    { name: "JumpToPrompt", ordinal: 46, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, { name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "from_offset", jsName: "fromOffset", type: { kind: "u32" } }, { name: "direction", jsName: "direction", type: { kind: "i8" } }, ] } },
  ] },
  ColumnState: { kind: "struct", fields: [
    { name: "tiles", jsName: "tiles", type: { kind: "seq", of: { kind: "ref", name: "TileState" } } },
    { name: "active_tile_idx", jsName: "activeTileIdx", type: { kind: "u64" } },
    { name: "width_proportion", jsName: "widthProportion", type: { kind: "f64" } },
    { name: "width_fixed_px", jsName: "widthFixedPx", type: { kind: "option", of: { kind: "f64" } } },
  ] },
  ImageDisplayMode: { kind: "enum", variants: [
    { name: "Cells", ordinal: 0, shape: { kind: "unit-struct" } },
    { name: "Pixels", ordinal: 1, shape: { kind: "unit-struct" } },
  ] },
  LayoutState: { kind: "struct", fields: [
    { name: "workspaces", jsName: "workspaces", type: { kind: "seq", of: { kind: "ref", name: "WorkspaceState" } } },
    { name: "active_workspace_idx", jsName: "activeWorkspaceIdx", type: { kind: "u64" } },
  ] },
  PaneDetailInfo: { kind: "struct", fields: [
    { name: "pane_id", jsName: "paneId", type: { kind: "u64" } },
    { name: "cols", jsName: "cols", type: { kind: "u16" } },
    { name: "rows", jsName: "rows", type: { kind: "u16" } },
    { name: "title", jsName: "title", type: { kind: "str" } },
    { name: "cwd", jsName: "cwd", type: { kind: "option", of: { kind: "str" } } },
    { name: "is_active", jsName: "isActive", type: { kind: "bool" } },
    { name: "workspace_idx", jsName: "workspaceIdx", type: { kind: "u64" } },
    { name: "column_idx", jsName: "columnIdx", type: { kind: "u64" } },
    { name: "tile_idx", jsName: "tileIdx", type: { kind: "u64" } },
  ] },
  PromptMarkInfo: { kind: "struct", fields: [
    { name: "prompt_line", jsName: "promptLine", type: { kind: "u64" } },
    { name: "output_line", jsName: "outputLine", type: { kind: "option", of: { kind: "u64" } } },
    { name: "done_line", jsName: "doneLine", type: { kind: "option", of: { kind: "u64" } } },
    { name: "exit_code", jsName: "exitCode", type: { kind: "option", of: { kind: "i32" } } },
    { name: "duration_ms", jsName: "durationMs", type: { kind: "option", of: { kind: "u64" } } },
  ] },
  ServerMessage: { kind: "enum", variants: [
    { name: "StateSync", ordinal: 0, shape: { kind: "struct", fields: [{ name: "layout", jsName: "layout", type: { kind: "ref", name: "LayoutState" } }, { name: "pane_ids", jsName: "paneIds", type: { kind: "seq", of: { kind: "u64" } } }, ] } },
    { name: "LayoutUpdate", ordinal: 1, shape: { kind: "struct", fields: [{ name: "layout", jsName: "layout", type: { kind: "ref", name: "LayoutState" } }, ] } },
    { name: "PaneCreated", ordinal: 2, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "column_idx", jsName: "columnIdx", type: { kind: "u64" } }, { name: "cols", jsName: "cols", type: { kind: "u16" } }, { name: "rows", jsName: "rows", type: { kind: "u16" } }, ] } },
    { name: "PaneClosed", ordinal: 3, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, ] } },
    { name: "ServerShutdown", ordinal: 4, shape: { kind: "unit-struct" } },
    { name: "ClipboardStore", ordinal: 5, shape: { kind: "struct", fields: [{ name: "data", jsName: "data", type: { kind: "str" } }, ] } },
    { name: "SessionList", ordinal: 6, shape: { kind: "struct", fields: [{ name: "sessions", jsName: "sessions", type: { kind: "seq", of: { kind: "ref", name: "SessionInfo" } } }, ] } },
    { name: "SessionSwitched", ordinal: 7, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "SessionKilled", ordinal: 8, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "Error", ordinal: 9, shape: { kind: "struct", fields: [{ name: "message", jsName: "message", type: { kind: "str" } }, ] } },
    { name: "Bell", ordinal: 10, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, ] } },
    { name: "CommandCompleted", ordinal: 11, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "duration_secs", jsName: "durationSecs", type: { kind: "u64" } }, { name: "exit_code", jsName: "exitCode", type: { kind: "option", of: { kind: "i32" } } }, ] } },
    { name: "Notification", ordinal: 12, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "title", jsName: "title", type: { kind: "str" } }, { name: "body", jsName: "body", type: { kind: "str" } }, ] } },
    { name: "ImagePlacement", ordinal: 13, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "image_id", jsName: "imageId", type: { kind: "u64" } }, { name: "col", jsName: "col", type: { kind: "u16" } }, { name: "row", jsName: "row", type: { kind: "u16" } }, { name: "width_cells", jsName: "widthCells", type: { kind: "u16" } }, { name: "height_cells", jsName: "heightCells", type: { kind: "u16" } }, { name: "pixel_width", jsName: "pixelWidth", type: { kind: "u32" } }, { name: "pixel_height", jsName: "pixelHeight", type: { kind: "u32" } }, { name: "display_mode", jsName: "displayMode", type: { kind: "ref", name: "ImageDisplayMode" } }, { name: "format", jsName: "format", type: { kind: "str" } }, { name: "data", jsName: "data", type: { kind: "seq", of: { kind: "u8" } } }, ] } },
    { name: "TitleChanged", ordinal: 14, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "title", jsName: "title", type: { kind: "str" } }, ] } },
    { name: "ImageDeleted", ordinal: 15, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, ] } },
    { name: "SessionInfoReply", ordinal: 16, shape: { kind: "struct", fields: [{ name: "info", jsName: "info", type: { kind: "ref", name: "SessionDetailInfo" } }, ] } },
    { name: "PaneListReply", ordinal: 17, shape: { kind: "struct", fields: [{ name: "panes", jsName: "panes", type: { kind: "seq", of: { kind: "ref", name: "PaneDetailInfo" } } }, ] } },
    { name: "CommandResult", ordinal: 18, shape: { kind: "struct", fields: [{ name: "success", jsName: "success", type: { kind: "bool" } }, { name: "message", jsName: "message", type: { kind: "str" } }, { name: "pane_id", jsName: "paneId", type: { kind: "option", of: { kind: "u64" } } }, ] } },
    { name: "LayoutReply", ordinal: 19, shape: { kind: "struct", fields: [{ name: "layout", jsName: "layout", type: { kind: "ref", name: "LayoutState" } }, { name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "TemplateApplied", ordinal: 20, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, ] } },
    { name: "TemplateList", ordinal: 21, shape: { kind: "struct", fields: [{ name: "templates", jsName: "templates", type: { kind: "seq", of: { kind: "ref", name: "TemplateInfo" } } }, ] } },
    { name: "TemplateSaved", ordinal: 22, shape: { kind: "struct", fields: [{ name: "template_name", jsName: "templateName", type: { kind: "str" } }, ] } },
    { name: "BounceEdge", ordinal: 23, shape: { kind: "struct", fields: [{ name: "direction", jsName: "direction", type: { kind: "ref", name: "BounceDirection" } }, ] } },
    { name: "Pong", ordinal: 24, shape: { kind: "struct", fields: [{ name: "seq", jsName: "seq", type: { kind: "u64" } }, { name: "client_time_us", jsName: "clientTimeUs", type: { kind: "u64" } }, ] } },
    { name: "PaneCapture", ordinal: 25, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, { name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "text", jsName: "text", type: { kind: "str" } }, { name: "truncated", jsName: "truncated", type: { kind: "bool" } }, ] } },
    { name: "PromptListReply", ordinal: 26, shape: { kind: "struct", fields: [{ name: "session_name", jsName: "sessionName", type: { kind: "str" } }, { name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "marks", jsName: "marks", type: { kind: "seq", of: { kind: "ref", name: "PromptMarkInfo" } } }, ] } },
    { name: "SetScrollOffset", ordinal: 27, shape: { kind: "struct", fields: [{ name: "pane_id", jsName: "paneId", type: { kind: "u64" } }, { name: "offset", jsName: "offset", type: { kind: "u32" } }, ] } },
  ] },
  SessionDetailInfo: { kind: "struct", fields: [
    { name: "name", jsName: "name", type: { kind: "str" } },
    { name: "running", jsName: "running", type: { kind: "bool" } },
    { name: "pane_count", jsName: "paneCount", type: { kind: "u64" } },
    { name: "client_count", jsName: "clientCount", type: { kind: "u64" } },
    { name: "workspace_count", jsName: "workspaceCount", type: { kind: "u64" } },
    { name: "active_workspace", jsName: "activeWorkspace", type: { kind: "u64" } },
  ] },
  SessionInfo: { kind: "struct", fields: [
    { name: "name", jsName: "name", type: { kind: "str" } },
    { name: "running", jsName: "running", type: { kind: "bool" } },
    { name: "pane_count", jsName: "paneCount", type: { kind: "u64" } },
    { name: "client_count", jsName: "clientCount", type: { kind: "u64" } },
  ] },
  TemplateInfo: { kind: "struct", fields: [
    { name: "name", jsName: "name", type: { kind: "str" } },
    { name: "description", jsName: "description", type: { kind: "option", of: { kind: "str" } } },
    { name: "workspace_count", jsName: "workspaceCount", type: { kind: "u64" } },
    { name: "total_panes", jsName: "totalPanes", type: { kind: "u64" } },
  ] },
  TileState: { kind: "struct", fields: [
    { name: "pane_id", jsName: "paneId", type: { kind: "u64" } },
    { name: "weight", jsName: "weight", type: { kind: "f32" } },
  ] },
  WorkspaceState: { kind: "struct", fields: [
    { name: "columns", jsName: "columns", type: { kind: "seq", of: { kind: "ref", name: "ColumnState" } } },
    { name: "active_column_idx", jsName: "activeColumnIdx", type: { kind: "u64" } },
  ] },
};
