//! Emit byte-identical CellDelta and FullPaneSync wire fixtures for the
//! `@ciri/codec` TS decoders. Output is a TS file with two named arrays
//! that the round-trip tests load directly.
//!
//! ```sh
//! cargo run -p ciri-protocol --example dump_frame_fixtures > frame_fixtures.ts
//! ```
//!
//! The wire bytes come from the same encoders the server uses
//! (`encode_cell_delta_streaming_framed`, `encode_full_pane_sync_payload`)
//! — minus the 5-byte frame header, which the FrameReader peels off
//! before handing the payload to the body decoder. The TS literals
//! describe the typed value the decoder must reconstruct.

use ciri_protocol::codec::{
    encode_cell_delta_streaming_framed, encode_full_pane_sync_payload,
};
use ciri_protocol::message::*;
use std::io::Write;

const AUTOGEN_HEADER: &str = "// AUTO-GENERATED by `cargo run -p ciri-protocol --example dump_frame_fixtures`.\n\
// Do not edit by hand. Regenerate after any change to the CellDelta /\n\
// FullPaneSync wire layout or to the curated fixture list in the\n\
// Rust example.\n\n";

fn main() {
    let mut out = String::new();
    out.push_str(AUTOGEN_HEADER);
    out.push_str(
        "import type { CellDelta, FullPaneSync } from \"../types.js\";\n\n",
    );
    out.push_str("export interface FrameFixture<T> { name: string; hex: string; value: T; }\n\n");

    out.push_str("export const CELL_DELTA_FIXTURES: FrameFixture<CellDelta>[] = [\n");
    for (name, hex_bytes, ts_lit) in cell_delta_fixtures() {
        out.push_str(&format!(
            "  {{ name: {:?}, hex: {:?}, value: {} }},\n",
            name, hex_bytes, ts_lit
        ));
    }
    out.push_str("];\n\n");

    out.push_str("export const FULL_PANE_SYNC_FIXTURES: FrameFixture<FullPaneSync>[] = [\n");
    for (name, hex_bytes, ts_lit) in full_pane_sync_fixtures() {
        out.push_str(&format!(
            "  {{ name: {:?}, hex: {:?}, value: {} }},\n",
            name, hex_bytes, ts_lit
        ));
    }
    out.push_str("];\n");

    std::io::stdout()
        .write_all(out.as_bytes())
        .expect("stdout");
}

// ─── CellDelta fixtures ─────────────────────────────────────────────

fn cell_delta_fixtures() -> Vec<(&'static str, String, String)> {
    let mut out = Vec::new();

    // Fixture A: single small region rendering "Hello" on row 0, cols 0..4.
    {
        let meta = PaneFrameMeta {
            pane_id: 42,
            generation: 5,
            cursor_line: 0,
            cursor_col: 5,
            cursor_shape: 0,
            mode_flags: 0,
            echo_ack: 0,
        };
        let cells = ascii_cells("Hello");
        let payload = encode_cell_delta_payload(
            &meta,
            80,
            vec![(0u16, 0u16, 4u16, cells.clone())],
        );
        let ts_value = format!(
            "{{ meta: {}, cols: 80, regions: [ {{ line: 0, left: 0, right: 4, cells: [{}] }} ] }}",
            meta_ts(&meta),
            cells_ts(&cells),
        );
        out.push(("Hello on row 0", hex(&payload), ts_value));
    }

    // Fixture B: two regions on different lines, mixed colors and flags.
    {
        let meta = PaneFrameMeta {
            pane_id: 1,
            generation: 11,
            cursor_line: 1,
            cursor_col: 2,
            cursor_shape: 1,
            mode_flags: MODE_ALT_SCREEN | MODE_BRACKETED_PASTE,
            echo_ack: 12345,
        };
        let red_bold = make_cell('R', NAMED_RED_COLOR, DEFAULT_BG_COLOR, FLAG_BOLD);
        let rgb_underline = make_cell(
            '#',
            PackedColor::rgb(0xff, 0x88, 0x00),
            PackedColor::rgb(0x11, 0x22, 0x33),
            FLAG_UNDERLINE,
        );
        let region1 = vec![red_bold, red_bold];
        let region2 = vec![rgb_underline];
        let payload = encode_cell_delta_payload(
            &meta,
            80,
            vec![
                (0u16, 10u16, 11u16, region1.clone()),
                (3u16, 5u16, 5u16, region2.clone()),
            ],
        );
        let ts_value = format!(
            "{{ meta: {}, cols: 80, regions: [ {{ line: 0, left: 10, right: 11, cells: [{}] }}, {{ line: 3, left: 5, right: 5, cells: [{}] }} ] }}",
            meta_ts(&meta),
            cells_ts(&region1),
            cells_ts(&region2),
        );
        out.push(("Two regions, mixed style", hex(&payload), ts_value));
    }

    // Fixture C: empty regions list (header-only). Wire validates the
    // header is decoded correctly without dereferencing any region.
    {
        let meta = PaneFrameMeta {
            pane_id: 7,
            generation: 0,
            cursor_line: -1,
            cursor_col: 0,
            cursor_shape: 2,
            mode_flags: 0,
            echo_ack: 0,
        };
        let payload = encode_cell_delta_payload(&meta, 132, vec![]);
        let ts_value = format!(
            "{{ meta: {}, cols: 132, regions: [] }}",
            meta_ts(&meta),
        );
        out.push(("Header only (no regions)", hex(&payload), ts_value));
    }

    out
}

// ─── FullPaneSync fixtures ──────────────────────────────────────────

fn full_pane_sync_fixtures() -> Vec<(&'static str, String, String)> {
    let mut out = Vec::new();

    // Fixture A: tiny 3×2 grid, all default cells, no extras, no cwd.
    {
        let meta = PaneFrameMeta {
            pane_id: 1,
            generation: 1,
            cursor_line: 0,
            cursor_col: 0,
            cursor_shape: 0,
            mode_flags: 0,
            echo_ack: 0,
        };
        let cells = vec![PackedCell::default(); 6];
        let sync = FullPaneSync {
            meta,
            cols: 3,
            rows: 2,
            title: String::new(),
            scrollback: Vec::new(),
            scrollback_rows: 0,
            scrollback_replace: false,
            cells: cells.clone(),
            grapheme_extras: GraphemeExtras::new(),
            hyperlink_extras: HyperlinkExtras::new(),
            cwd: None,
        };
        let payload = encode_full_pane_sync_payload(&sync).expect("encode");
        let ts_value = format!(
            "{{ meta: {}, cols: 3, rows: 2, title: \"\", scrollback: [], scrollbackRows: 0, scrollbackReplace: false, cells: [{}], graphemeExtras: new Map<number, string>(), cellLinks: new Map<number, number>(), linkMap: new Map<number, string>(), cwd: null }}",
            meta_ts(&meta),
            cells_ts(&cells),
        );
        out.push(("3x2 default", hex(&payload), ts_value));
    }

    // Fixture B: 4×1 viewport with title, cwd, two grapheme extras and a
    // hyperlink covering one cell.
    {
        let meta = PaneFrameMeta {
            pane_id: 2,
            generation: 99,
            cursor_line: 0,
            cursor_col: 3,
            cursor_shape: 0,
            mode_flags: 0,
            echo_ack: 17,
        };
        let cells = vec![
            ascii_cell('a'),
            // U+1F600 grinning face: a 4-byte UTF-8 scalar that lives in
            // the cell slot directly.
            make_cell('\u{1F600}', DEFAULT_FG_COLOR, DEFAULT_BG_COLOR, 0),
            ascii_cell('b'),
            ascii_cell('c'),
        ];
        let mut grapheme_extras = GraphemeExtras::new();
        // Cell index 1 (the emoji) has a ZWJ-extended sequence: the
        // base codepoint lives in the cell slot, the rest of the
        // sequence lives in graphemeExtras under that cellIndex.
        grapheme_extras.push(1, "\u{200D}\u{1F4BB}");
        let mut hyperlink_extras = HyperlinkExtras::new();
        hyperlink_extras.cell_links.push((2, 1));
        hyperlink_extras
            .link_map
            .push((1, "https://example.com".to_string()));
        let sync = FullPaneSync {
            meta,
            cols: 4,
            rows: 1,
            title: "shell".to_string(),
            scrollback: Vec::new(),
            scrollback_rows: 0,
            scrollback_replace: false,
            cells: cells.clone(),
            grapheme_extras: grapheme_extras.clone(),
            hyperlink_extras: hyperlink_extras.clone(),
            cwd: Some("/home/u".to_string()),
        };
        let payload = encode_full_pane_sync_payload(&sync).expect("encode");
        let ts_value = format!(
            "{{ meta: {}, cols: 4, rows: 1, title: \"shell\", scrollback: [], scrollbackRows: 0, scrollbackReplace: false, cells: [{}], graphemeExtras: new Map<number, string>([[1, \"\\u200D\\u{{1F4BB}}\"]]), cellLinks: new Map<number, number>([[2, 1]]), linkMap: new Map<number, string>([[1, \"https://example.com\"]]), cwd: \"/home/u\" }}",
            meta_ts(&meta),
            cells_ts(&cells),
        );
        out.push((
            "4x1 with title, cwd, grapheme + hyperlink",
            hex(&payload),
            ts_value,
        ));
    }

    // Fixture C: 2×1 viewport with a 1-row scrollback (scrollback_replace).
    {
        let meta = PaneFrameMeta {
            pane_id: 3,
            generation: 200,
            cursor_line: 0,
            cursor_col: 1,
            cursor_shape: 0,
            mode_flags: 0,
            echo_ack: 0,
        };
        let scrollback = vec![ascii_cell('o'), ascii_cell('k')];
        let viewport = vec![ascii_cell('h'), ascii_cell('i')];
        let sync = FullPaneSync {
            meta,
            cols: 2,
            rows: 1,
            title: String::new(),
            scrollback: scrollback.clone(),
            scrollback_rows: 1,
            scrollback_replace: true,
            cells: viewport.clone(),
            grapheme_extras: GraphemeExtras::new(),
            hyperlink_extras: HyperlinkExtras::new(),
            cwd: None,
        };
        let payload = encode_full_pane_sync_payload(&sync).expect("encode");
        let ts_value = format!(
            "{{ meta: {}, cols: 2, rows: 1, title: \"\", scrollback: [{}], scrollbackRows: 1, scrollbackReplace: true, cells: [{}], graphemeExtras: new Map<number, string>(), cellLinks: new Map<number, number>(), linkMap: new Map<number, string>(), cwd: null }}",
            meta_ts(&meta),
            cells_ts(&scrollback),
            cells_ts(&viewport),
        );
        out.push(("2x1 with 1-row scrollback (replace)", hex(&payload), ts_value));
    }

    out
}

// ─── Helpers ────────────────────────────────────────────────────────

fn encode_cell_delta_payload(
    meta: &PaneFrameMeta,
    cols: u16,
    regions: Vec<(u16, u16, u16, Vec<PackedCell>)>,
) -> Vec<u8> {
    let mut buf = Vec::new();
    let region_meta: Vec<(u16, u16, u16)> =
        regions.iter().map(|(l, le, r, _)| (*l, *le, *r)).collect();
    let cells_by_region: Vec<Vec<PackedCell>> =
        regions.into_iter().map(|(_, _, _, c)| c).collect();
    let mut idx = 0usize;
    encode_cell_delta_streaming_framed(
        &mut buf,
        meta,
        cols,
        &region_meta,
        |_line, _left, _right, enc| {
            for cell in &cells_by_region[idx] {
                enc.push_cell(cell);
            }
            idx += 1;
        },
    )
    .expect("encode_cell_delta_streaming_framed");
    // The framed encoder writes [tag][u32 LE len][payload[..]] AND may
    // toggle the tag to the LZ4 variant when compression wins. The body
    // decoder consumes only `payload`, so strip the 5-byte header for
    // fixtures.
    //
    // The LZ4 path is irrelevant here: our tiny fixtures never trip
    // compression. But if a future fixture does, the FrameReader (which
    // is what real callers use) takes care of decompressing before
    // calling our body decoder anyway — the test still passes through
    // the same decoded payload.
    assert!(buf.len() >= 5, "encoded frame too short");
    buf.drain(0..5);
    buf
}

fn make_cell(ch: char, fg: PackedColor, bg: PackedColor, flags: u16) -> PackedCell {
    let mut cell = PackedCell::default();
    cell.set_ch(ch);
    cell.fg = fg;
    cell.bg = bg;
    cell.flags = flags.to_le_bytes();
    cell
}

fn ascii_cell(ch: char) -> PackedCell {
    make_cell(ch, DEFAULT_FG_COLOR, DEFAULT_BG_COLOR, 0)
}

fn ascii_cells(s: &str) -> Vec<PackedCell> {
    s.chars().map(ascii_cell).collect()
}

const NAMED_RED_COLOR: PackedColor = PackedColor::named(NAMED_RED);
const DEFAULT_FG_COLOR: PackedColor = PackedColor::named(NAMED_FOREGROUND);
const DEFAULT_BG_COLOR: PackedColor = PackedColor::named(NAMED_BACKGROUND);

fn meta_ts(m: &PaneFrameMeta) -> String {
    format!(
        "{{ paneId: {}n, generation: {}n, cursorLine: {}, cursorCol: {}, cursorShape: {}, modeFlags: {}, echoAck: {}n }}",
        m.pane_id,
        m.generation,
        m.cursor_line,
        m.cursor_col,
        m.cursor_shape,
        m.mode_flags,
        m.echo_ack,
    )
}

fn cells_ts(cells: &[PackedCell]) -> String {
    let mut parts: Vec<String> = Vec::with_capacity(cells.len());
    for c in cells {
        let ch = c.ch();
        parts.push(format!(
            "{{ ch: {:?}, fg: {}, bg: {}, flags: {} }}",
            ch.to_string(),
            color_ts(c.fg),
            color_ts(c.bg),
            c.flags_u16(),
        ));
    }
    parts.join(", ")
}

fn color_ts(c: PackedColor) -> String {
    match c.tag {
        COLOR_NAMED => format!("{{ kind: \"named\", index: {} }}", c.b1),
        COLOR_INDEXED => format!("{{ kind: \"indexed\", index: {} }}", c.b1),
        COLOR_RGB => format!(
            "{{ kind: \"rgb\", r: {}, g: {}, b: {} }}",
            c.b1, c.b2, c.b3
        ),
        other => panic!("unknown PackedColor tag {other}"),
    }
}

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}
