//! Emit a TypeScript file mirroring every wire-format constant in
//! ciri-protocol. Run with:
//!
//! ```sh
//! cargo run -p ciri-protocol --example dump_constants > \
//!     web/packages/ciri-codec/src/constants.ts
//! ```
//!
//! Re-run after any change to message.rs / codec/state_machine.rs /
//! codec/frame.rs that touches a constant value; otherwise the TS
//! decoder will silently disagree with the wire.

use ciri_protocol::codec::*;
use ciri_protocol::message::*;

fn main() {
    println!("// AUTO-GENERATED by `cargo run -p ciri-protocol --example dump_constants`.");
    println!("// Do not edit by hand. Regenerate after touching the Rust constants.");
    println!();
    println!("// ── Handshake / framing ───────────────────────────────");
    println!("export const WIRE_PROTOCOL_VERSION = {WIRE_PROTOCOL_VERSION};");
    println!("export const SERVER_HELLO_LEN = {SERVER_HELLO_LEN};");
    println!("export const MAX_DATA_FRAME_LEN = {MAX_DATA_FRAME_LEN};");
    println!();
    println!("// Frame tag bytes (server → client + client → server).");
    println!("// These are stable wire values — see frame.rs for definitions.");
    println!("export const TAG_CLIENT_MSG = 0x01;");
    println!("export const TAG_SERVER_MSG = 0x10;");
    println!("export const TAG_CELL_DELTA = 0x20;");
    println!("export const TAG_FULL_PANE_SYNC = 0x21;");
    println!("export const TAG_CELL_DELTA_LZ4 = 0x22;");
    println!("export const TAG_FULL_PANE_SYNC_LZ4 = 0x23;");
    println!();
    println!("// ── PackedCell layout ─────────────────────────────────");
    println!("export const PACKED_CELL_SIZE = {PACKED_CELL_SIZE};");
    println!("export const DEFAULT_CELL_CHAR = 0x{:02x}; // space", DEFAULT_CELL_CHAR as u32);
    println!("export const DEFAULT_CELL_FLAGS = 0x{DEFAULT_CELL_FLAGS:04x};");
    println!();
    println!("// ── Color discriminant tags ───────────────────────────");
    println!("export const COLOR_NAMED = {COLOR_NAMED};");
    println!("export const COLOR_RGB = {COLOR_RGB};");
    println!("export const COLOR_INDEXED = {COLOR_INDEXED};");
    println!();
    println!("// ── Named color IDs ───────────────────────────────────");
    for (name, value) in [
        ("NAMED_BLACK", NAMED_BLACK),
        ("NAMED_RED", NAMED_RED),
        ("NAMED_GREEN", NAMED_GREEN),
        ("NAMED_YELLOW", NAMED_YELLOW),
        ("NAMED_BLUE", NAMED_BLUE),
        ("NAMED_MAGENTA", NAMED_MAGENTA),
        ("NAMED_CYAN", NAMED_CYAN),
        ("NAMED_WHITE", NAMED_WHITE),
        ("NAMED_BRIGHT_BLACK", NAMED_BRIGHT_BLACK),
        ("NAMED_BRIGHT_RED", NAMED_BRIGHT_RED),
        ("NAMED_BRIGHT_GREEN", NAMED_BRIGHT_GREEN),
        ("NAMED_BRIGHT_YELLOW", NAMED_BRIGHT_YELLOW),
        ("NAMED_BRIGHT_BLUE", NAMED_BRIGHT_BLUE),
        ("NAMED_BRIGHT_MAGENTA", NAMED_BRIGHT_MAGENTA),
        ("NAMED_BRIGHT_CYAN", NAMED_BRIGHT_CYAN),
        ("NAMED_BRIGHT_WHITE", NAMED_BRIGHT_WHITE),
        ("NAMED_FOREGROUND", NAMED_FOREGROUND),
        ("NAMED_BACKGROUND", NAMED_BACKGROUND),
        ("NAMED_CURSOR", NAMED_CURSOR),
        ("NAMED_DIM_BLACK", NAMED_DIM_BLACK),
        ("NAMED_DIM_RED", NAMED_DIM_RED),
        ("NAMED_DIM_GREEN", NAMED_DIM_GREEN),
        ("NAMED_DIM_YELLOW", NAMED_DIM_YELLOW),
        ("NAMED_DIM_BLUE", NAMED_DIM_BLUE),
        ("NAMED_DIM_MAGENTA", NAMED_DIM_MAGENTA),
        ("NAMED_DIM_CYAN", NAMED_DIM_CYAN),
        ("NAMED_DIM_WHITE", NAMED_DIM_WHITE),
        ("NAMED_BRIGHT_FOREGROUND", NAMED_BRIGHT_FOREGROUND),
        ("NAMED_DIM_FOREGROUND", NAMED_DIM_FOREGROUND),
    ] {
        println!("export const {name} = {value};");
    }
    println!();
    println!("// ── Cell flag bits ────────────────────────────────────");
    for (name, value) in [
        ("FLAG_WIDE_CHAR", FLAG_WIDE_CHAR),
        ("FLAG_WIDE_CHAR_SPACER", FLAG_WIDE_CHAR_SPACER),
        ("FLAG_BOLD", FLAG_BOLD),
        ("FLAG_ITALIC", FLAG_ITALIC),
        ("FLAG_UNDERLINE", FLAG_UNDERLINE),
        ("FLAG_INVERSE", FLAG_INVERSE),
        ("FLAG_DIM", FLAG_DIM),
        ("FLAG_STRIKEOUT", FLAG_STRIKEOUT),
        ("FLAG_HIDDEN", FLAG_HIDDEN),
        ("FLAG_UNDERLINE_STYLE_MASK", FLAG_UNDERLINE_STYLE_MASK),
        ("FLAG_UNDERLINE_DOUBLE", FLAG_UNDERLINE_DOUBLE),
        ("FLAG_UNDERLINE_CURLY", FLAG_UNDERLINE_CURLY),
        ("FLAG_UNDERLINE_DOTTED", FLAG_UNDERLINE_DOTTED),
        ("FLAG_UNDERLINE_DASHED", FLAG_UNDERLINE_DASHED),
        ("FLAG_WRAPLINE", FLAG_WRAPLINE),
        ("FLAG_HYPERLINK", FLAG_HYPERLINK),
    ] {
        println!("export const {name} = 0x{value:04x};");
    }
    println!();
    println!("// ── Terminal mode flags ───────────────────────────────");
    for (name, value) in [
        ("MODE_MOUSE_REPORT", MODE_MOUSE_REPORT),
        ("MODE_ALT_SCREEN", MODE_ALT_SCREEN),
        ("MODE_SHELL_INTEGRATION", MODE_SHELL_INTEGRATION),
        ("MODE_KITTY_KEYBOARD", MODE_KITTY_KEYBOARD),
        ("MODE_BRACKETED_PASTE", MODE_BRACKETED_PASTE),
        ("MODE_FOCUS_EVENT", MODE_FOCUS_EVENT),
        ("MODE_SYNCHRONIZED_OUTPUT", MODE_SYNCHRONIZED_OUTPUT),
        ("MODE_KITTY_REPORT_EVENTS", MODE_KITTY_REPORT_EVENTS),
        ("MODE_KITTY_REPORT_ALTERNATES", MODE_KITTY_REPORT_ALTERNATES),
        ("MODE_KITTY_REPORT_ALL", MODE_KITTY_REPORT_ALL),
        ("MODE_KITTY_REPORT_TEXT", MODE_KITTY_REPORT_TEXT),
        ("MODE_PASSWORD_INPUT", MODE_PASSWORD_INPUT),
        ("MODE_APP_CURSOR", MODE_APP_CURSOR),
        ("MODE_APP_KEYPAD", MODE_APP_KEYPAD),
        ("MODE_ALTERNATE_SCROLL", MODE_ALTERNATE_SCROLL),
        ("MODE_KITTY_ALL", MODE_KITTY_ALL),
    ] {
        println!("export const {name} = 0x{value:04x};");
    }
    println!();
    println!("// ── Cursor shape ──────────────────────────────────────");
    for (name, value) in [
        ("CURSOR_BLOCK", CURSOR_BLOCK),
        ("CURSOR_UNDERLINE", CURSOR_UNDERLINE),
        ("CURSOR_BEAM", CURSOR_BEAM),
        ("CURSOR_HIDDEN", CURSOR_HIDDEN),
        ("CURSOR_HOLLOW_BLOCK", CURSOR_HOLLOW_BLOCK),
    ] {
        println!("export const {name} = {value};");
    }
    println!();
    println!("// ── State-machine cell opcodes ────────────────────────");
    for (name, value) in [
        ("OP_SET_FG", OP_SET_FG),
        ("OP_SET_BG", OP_SET_BG),
        ("OP_SET_FLAGS", OP_SET_FLAGS),
        ("OP_SET_FG_BG", OP_SET_FG_BG),
        ("OP_RESET", OP_RESET),
        ("OP_SET_FG_NAMED", OP_SET_FG_NAMED),
        ("OP_SET_BG_NAMED", OP_SET_BG_NAMED),
        ("OP_SET_FG_INDEXED", OP_SET_FG_INDEXED),
        ("OP_SET_BG_INDEXED", OP_SET_BG_INDEXED),
        ("OP_CHAR1", OP_CHAR1),
        ("OP_CHARS", OP_CHARS),
        ("OP_REPEAT", OP_REPEAT),
        ("OP_CHARS_LONG", OP_CHARS_LONG),
        ("OP_ASCII", OP_ASCII),
        ("OP_ASCII_REPEAT", OP_ASCII_REPEAT),
        ("OP_END", OP_END),
    ] {
        println!("export const {name} = 0x{value:02x};");
    }
}
