[package]
name = "ciri-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
rmp-serde = { workspace = true }
bytemuck = { workspace = true }
zerocopy = { workspace = true }
bytes = { workspace = true }
dirs = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net"] }
lz4_flex = "0.11"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
lz4_flex = "0.11"
proptest = "1"
tokio-test = "0.4"
tokio = { workspace = true, features = ["full"] }

[[bench]]
name = "protocol_decode"
harness = false

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
nix = { workspace = true }
