[package]
name = "loom-ui"
version.workspace = true
edition.workspace = true

[dependencies]
loom-motion = { workspace = true }
loom-config = { workspace = true }
loom-render = { workspace = true }
log = { workspace = true }
smallvec = { workspace = true }
smol_str = { workspace = true }
taffy = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "chrome_paint"
harness = false
