[package]
name = "ciritty-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ciritty-server"
path = "src/main.rs"

[dependencies]
ciri-term = { workspace = true }
ciri-layout = { path = "../ciri-layout" }
ciri-protocol = { workspace = true }
ciri-session = { workspace = true }
ciri-config = { workspace = true }
ciri-procinfo = { workspace = true }
rmp-serde = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
percent-encoding = { workspace = true }
subtle = { workspace = true }
zeroize = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
dirs = { workspace = true }
tray-icon = "0.19"
image = { version = "0.25", default-features = false, features = ["png"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
windows-sys = { version = "0.59", features = ["Win32_UI_WindowsAndMessaging"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-app-kit = { version = "0.3", features = ["NSApplication", "NSRunningApplication", "NSEvent"] }
objc2-foundation = { version = "0.3", features = ["NSObjCRuntime", "NSString", "NSDate"] }

[dev-dependencies]
rstest = "0.26"
tempfile = "3"
