foreground = "#FFFFFF"
background = "#282C34"
black = "#1D1F21"
red = "#CC6666"
green = "#B5BD68"
yellow = "#F0C674"
blue = "#81A2BE"
magenta = "#B294BB"
cyan = "#8ABEB7"
white = "#C5C8C6"
bright_black = "#666666"
bright_red = "#D54E53"
bright_green = "#B9CA4A"
bright_yellow = "#E7C547"
bright_blue = "#7AA6DA"
bright_magenta = "#C397D8"
bright_cyan = "#70C0B1"
bright_white = "#EAEAEA"
ui_background = "#282C34"
overview_background = "#666666"
statusbar_background = "#1D1F21"
border_active = "#81A2BE"
border_inactive = "#3E4452"
accent = "#81A2BE"
statusbar_dim = "#666666"
mode_broadcast = "#F0C674"
