foreground = "#EBDBB2"
background = "#282828"
black = "#282828"
red = "#CC241D"
green = "#98971A"
yellow = "#D79921"
blue = "#458588"
magenta = "#B16286"
cyan = "#689D6A"
white = "#A89984"
bright_black = "#928374"
bright_red = "#FB4934"
bright_green = "#B8BB26"
bright_yellow = "#FABD2F"
bright_blue = "#83A598"
bright_magenta = "#D3869B"
bright_cyan = "#8EC07C"
bright_white = "#EBDBB2"
ui_background = "#282828"
overview_background = "#665C54"
statusbar_background = "#1D2021"
border_active = "#FABD2F"
border_inactive = "#504945"
accent = "#B8BB26"
statusbar_dim = "#928374"
mode_broadcast = "#FABD2F"
