[package]
name = "loom-term"
version.workspace = true
edition.workspace = true

[dependencies]
alacritty_terminal = { workspace = true }
loom-protocol = { workspace = true }
portable-pty = "0.8"
base64 = { workspace = true }
winnow = { workspace = true }
percent-encoding = { workspace = true }
colorsys = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
gethostname = "1.1"

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
